# Generated by Django 2.2.4 on 2019-10-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(default='', max_length=15, verbose_name='Личный код доступа'),
        ),
    ]
