# Generated by Django 2.2.4 on 2019-10-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_link',
            field=models.CharField(default='', max_length=20, verbose_name='Ссылка на пользователя'),
        ),
    ]
