# Generated by Django 2.2.4 on 2019-11-03 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_student_id_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondaylink',
            name='is_change',
            field=models.BooleanField(default=False, verbose_name='Замена'),
        ),
        migrations.AddField(
            model_name='lessondaylink',
            name='week',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='student',
            name='enter_date',
            field=models.DateField(null=True, verbose_name='Дата поступления студента'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(max_length=25, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения студента'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Code', verbose_name='Личный код доступа'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_link',
            field=models.CharField(default='', max_length=20, verbose_name='Ссылка на пользователя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Контактный номер телефона', max_length=31, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(max_length=25, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lessondaylink',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Lesson', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Code', verbose_name='Личный код доступа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ядро пользователя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ядро пользователя'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Баланс')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Действительный')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ядро пользователя')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=10)),
                ('link', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ядро пользователя')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
    ]
